/* ============================================================
 * 星轨 ORBIT · 内容数据
 * 所有文案与轨道参数集中于此 —— 改这里即可，无需动场景代码。
 * status: 'online' | 'offline'  （offline 时档案卡显示离线态，但仍可点击跳转）
 * ============================================================ */

export const STAR = {
  domain: 'mpsxx.top',
  zh: '主星',
  desc: '这片星系的引力中心。主站尚在建设中 —— 你正在看的这页星图，就是它现在的样子。',
};

export const SITES = [
  {
    id: 'blog',
    no: '01',
    zh: '喵思录',
    en: 'MEOW ARCHIVE',
    kind: '个人博客',
    domain: 'blog.mpsxx.top',
    alt: null,
    url: 'https://blog.mpsxx.top',
    desc: '「喵」思录 —— 技术梳理、心得体会与轻食菜谱，附年终总结、工具箱，和一台常驻的音乐台。',
    tags: ['写作', '技术', '轻食'],
    status: 'online',
    hue: '#E8C87E',
    size: 0.46,
    orbit: 8.0,
    speed: 0.16,
    incl: 3.2,
    phase: 0.4,
  },
  {
    id: 'blogs',
    no: '02',
    zh: '新博客',
    en: 'NEW BLOG',
    kind: '个人博客 · 新站',
    domain: 'blogs.mpsxx.top',
    alt: null,
    url: 'https://blogs.mpsxx.top',
    desc: '「喵」思录的下一站 —— 站长的新博客，正在持续写作中。',
    tags: ['写作', '新站'],
    status: 'online',
    hue: '#C8E89E',
    size: 0.44,
    orbit: 10.1,
    speed: 0.135,
    incl: -4.4,
    phase: 1.7,
  },
  {
    id: 'img',
    no: '03',
    zh: '随机图鉴',
    en: 'RANDOM IMAGERY',
    kind: '图片 API',
    domain: 'img.mpsxx.top',
    alt: null,
    url: 'https://img.mpsxx.top',
    desc: '随机图片接口 —— 访问 /api 即返回一张随机图片，支持 json / raw 两种输出，源码开源在 GitHub。',
    tags: ['API', '开源', '图床'],
    status: 'online',
    hue: '#8AB8E0',
    size: 0.38,
    orbit: 12.2,
    speed: 0.115,
    incl: 5.1,
    phase: 2.9,
  },
  {
    id: 'food',
    no: '04',
    zh: '冰箱管家',
    en: 'FRIDGE AI',
    kind: '食材管理',
    domain: 'food.mpsxx.top',
    alt: null,
    url: 'https://food.mpsxx.top',
    desc: 'FridgeAI 智能食材管家 —— 记录冰箱里的每一份食材，让新鲜被看见、被记住、被吃掉。',
    tags: ['AI', '生活', '工具'],
    status: 'online',
    hue: '#7ED8B8',
    size: 0.42,
    orbit: 14.3,
    speed: 0.1,
    incl: -3.6,
    phase: 4.1,
  },
  {
    id: 'bot',
    no: '05',
    zh: '云端助理',
    en: 'CHAT PILOT',
    kind: '机器人云管理',
    domain: 'bot.mpsxx.top',
    alt: null,
    url: 'https://bot.mpsxx.top',
    desc: '「聊天助理 · 云管理」—— 管理多账号登录态、配置 LLM 接口、调度消息收发与长期记忆的云端控制台。',
    tags: ['LLM', '机器人', '调度'],
    status: 'online',
    hue: '#A88ED8',
    size: 0.5,
    orbit: 16.4,
    speed: 0.088,
    incl: 6.2,
    phase: 5.2,
  },
  {
    id: 'markbook',
    no: '06',
    zh: '收藏星簿',
    en: 'MARKBOOK',
    kind: '书签收藏',
    domain: 'markbook.mpsxx.top',
    alt: null,
    url: 'https://markbook.mpsxx.top',
    desc: '一枚安静的书签收藏簿，整理散落各处的星图坐标。目前源站无响应，暂时离线维护中。',
    tags: ['书签', '收藏'],
    status: 'offline',
    hue: '#D88EA8',
    size: 0.36,
    orbit: 18.5,
    speed: 0.078,
    incl: -5.4,
    phase: 0.9,
  },
  {
    id: 'cf',
    no: '07',
    zh: '边缘服务台',
    en: 'EDGE WORKS',
    kind: 'Workers 服务',
    domain: 'cf.mpsxx.top',
    alt: 'api.cf.mpsxx.top',
    url: 'https://cf.mpsxx.top',
    desc: '跑在 Cloudflare Workers 上的小服务集合，附 api.cf 开放接口。当前源站无响应，等待重新点火。',
    tags: ['Workers', 'Edge', 'API'],
    status: 'offline',
    hue: '#E89E6E',
    size: 0.4,
    orbit: 20.6,
    speed: 0.068,
    incl: 4.0,
    phase: 3.4,
  },
];

/* 已退役子域名（仅存在于历史证书记录中） */
export const RETIRED = [
  'memos', 'twikoo', 'umami', 'meting', 'roomgame',
  'tool', 'tools-docx', 'friend', 'jx', 'cc',
];

export const onlineCount = SITES.filter(s => s.status === 'online').length;
